name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Create docs folder and move the generated SVG
        run: |
          mkdir -p docs  # Create docs folder if it doesn't exist
          mv dist/snake.svg docs/snake.svg  # Move the generated SVG to the docs folder
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/snake.svg  # Stage the new SVG file
          git commit -m "Update snake animation"
          git push origin main  # Push the changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
